# Form implementation generated from reading ui file 'DeleteDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteDialog(object):
    def setupUi(self, DeleteDialog):
        DeleteDialog.setObjectName("DeleteDialog")
        DeleteDialog.resize(399, 129)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dollar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        DeleteDialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(DeleteDialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(DeleteDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 70, 160, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Yes_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Yes_button.setObjectName("Yes_button")
        self.horizontalLayout.addWidget(self.Yes_button)
        self.No_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.No_button.setObjectName("No_button")
        self.horizontalLayout.addWidget(self.No_button)

        self.retranslateUi(DeleteDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteDialog)

    def retranslateUi(self, DeleteDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteDialog.setWindowTitle(_translate("DeleteDialog", "Внимание!"))
        self.label.setText(_translate("DeleteDialog", "Вы действительно хотите удалить выбранные записи?"))
        self.Yes_button.setText(_translate("DeleteDialog", "Да"))
        self.No_button.setText(_translate("DeleteDialog", "Нет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteDialog = QtWidgets.QDialog()
    ui = Ui_DeleteDialog()
    ui.setupUi(DeleteDialog)
    DeleteDialog.show()
    sys.exit(app.exec())
