# Form implementation generated from reading ui file 'EditDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditDialog(object):
    def setupUi(self, EditDialog):
        EditDialog.setObjectName("EditDialog")
        EditDialog.resize(656, 208)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dollar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EditDialog.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(EditDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 60, 551, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_torg_date = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_torg_date.setFont(font)
        self.label_torg_date.setObjectName("label_torg_date")
        self.horizontalLayout.addWidget(self.label_torg_date)
        self.label_regnum = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_regnum.setFont(font)
        self.label_regnum.setObjectName("label_regnum")
        self.horizontalLayout.addWidget(self.label_regnum)
        self.label_price = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_price.setFont(font)
        self.label_price.setObjectName("label_price")
        self.horizontalLayout.addWidget(self.label_price)
        self.label_gain_end = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_gain_end.setFont(font)
        self.label_gain_end.setObjectName("label_gain_end")
        self.horizontalLayout.addWidget(self.label_gain_end)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(EditDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 100, 551, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_torg_date = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.line_torg_date.setEnabled(False)
        self.line_torg_date.setObjectName("line_torg_date")
        self.horizontalLayout_3.addWidget(self.line_torg_date)
        self.line_regnum = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.line_regnum.setEnabled(False)
        self.line_regnum.setText("")
        self.line_regnum.setObjectName("line_regnum")
        self.horizontalLayout_3.addWidget(self.line_regnum)
        self.line_price = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.line_price.setObjectName("line_price")
        self.horizontalLayout_3.addWidget(self.line_price)
        self.line_gain_end = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.line_gain_end.setObjectName("line_gain_end")
        self.horizontalLayout_3.addWidget(self.line_gain_end)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(EditDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(240, 160, 160, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.button_ok.setObjectName("button_ok")
        self.horizontalLayout_2.addWidget(self.button_ok)
        self.button_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_2.addWidget(self.button_cancel)
        self.textBrowser = QtWidgets.QTextBrowser(EditDialog)
        self.textBrowser.setGeometry(QtCore.QRect(50, 10, 256, 51))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(EditDialog)
        QtCore.QMetaObject.connectSlotsByName(EditDialog)

    def retranslateUi(self, EditDialog):
        _translate = QtCore.QCoreApplication.translate
        EditDialog.setWindowTitle(_translate("EditDialog", "Редактирование записи"))
        self.label_torg_date.setText(_translate("EditDialog", "Дата торгов"))
        self.label_regnum.setText(_translate("EditDialog", "Код бумаги"))
        self.label_price.setText(_translate("EditDialog", "Текущая цена"))
        self.label_gain_end.setText(_translate("EditDialog", "Текущая доходность"))
        self.button_ok.setText(_translate("EditDialog", "Ок"))
        self.button_cancel.setText(_translate("EditDialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditDialog = QtWidgets.QDialog()
    ui = Ui_EditDialog()
    ui.setupUi(EditDialog)
    EditDialog.show()
    sys.exit(app.exec())
